services:
  - type: web
    name: sigverify-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Signature_Verification.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ADMIN_LOGIN_ID
        value: admin
      - key: ADMIN_PASSWORD
        value: admin
      - key: PYTHON_VERSION
        value: "3.11.0"
